const fs = require("fs");
/*
const form_configs = { billing: 1, payment: 2, contact: 3 };

const form_field_configs = [
    {
        form_config_id: 1,
        name: "client_fullname",
        label: "To:",
        field_type: "text",
        field_value_type: "string",
        options: null,
        position: 1,
        required: true,
    },
    {
        form_config_id: 1,
        name: "client_number",
        label: "NDIS:",
        field_type: "text",
        field_value_type: "string",
        options: null,
        position: 2,
        required: true,
    },
    {
        form_config_id: 1,
        name: "client_address",
        label: "Address:",
        field_type: "text",
        field_value_type: "string",
        options: null,
        position: 3,
        required: true,
    },
];
const table_configs = {
    1: { title: "edit", data: "service" },
    2: { title: "ndis", data: "service" },
};

const table_field_configs = [
    {
        table_config_id: 1,
        name: "service_date",
        label: "Service Date",
        field_type: "input",
        field_value_type: "date",
        options: null,
        position: 1,
        required: true,
    },
    {
        table_config_id: 1,
        name: "line_number",
        label: "Line Number",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 2,
        required: true,
    },
    {
        table_config_id: 1,
        name: "description",
        label: "Description",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 3,
        required: true,
    },
    {
        table_config_id: 1,
        name: "km",
        label: "KM",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 4,
        required: true,
    },
    {
        table_config_id: 1,
        name: "km_rate",
        label: "Rate(KM)",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 5,
        required: true,
    },
    {
        table_config_id: 1,
        name: "hour",
        label: "Hours",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 6,
        required: true,
    },
    {
        table_config_id: 1,
        name: "hour_rate",
        label: "Rate(Hours)",
        field_type: "input",
        field_value_type: "number",
        options: null,
        position: 7,
        required: true,
    },
    {
        table_config_id: 1,
        name: "ammount",
        label: "Ammount",
        field_type: "total",
        field_value_type: "number",
        options: null,
        position: 8,
        required: true,
    },
    {
        table_config_id: 2,
        name: "service_date",
        label: "Service Date",
        field_type: "text",
        field_value_type: "date",
        options: null,
        position: 1,
        required: true,
    },
    {
        table_config_id: 2,
        name: "line_number",
        label: "Line Number",
        field_type: "text",
        field_value_type: "number",
        options: null,
        position: 2,
        required: true,
    },
    {
        table_config_id: 2,
        name: "description",
        label: "Description",
        field_type: "text",
        field_value_type: "number",
        options: null,
        position: 3,
        required: true,
    },
    {
        table_config_id: 2,
        name: "km_rate",
        label: "Distance & Agreed Rate",
        field_type: "text",
        field_value_type: "custom",
        options: null,
        position: 4,
        required: true,
    },
    {
        table_config_id: 2,
        name: "km_rate",
        label: "Duration & Agreed Rate",
        field_type: "text",
        field_value_type: "custom",
        options: null,
        position: 5,
        required: true,
    },
    {
        table_config_id: 2,
        name: "ammount",
        label: "Ammount",
        field_type: "text",
        field_value_type: "number",
        options: null,
        position: 6,
        required: true,
    },
];
const serviceHeadings = [
    ["edit", "Service Date", "Description", "KM", "Rate(KM)", "Hours", "Rate(Hours)", "Ammount"],
    [
        "ndis",
        "Service Date",
        "Line Number",
        "Description",
        "Distance & Agreed Rate",
        "Duration & Agreed Rate",
        "Ammount",
    ],
];
const emptyService = {
    service_date: new Date("2024-01-01T16:00:00.000Z"),
    line_number: "",
    description: "",
    km: 0,
    km_rate: 0.85,
    hour: 0,
    hour_rate: 50,
};
const emptyInvoice = {
    invoice_id: "",
    invoice_type: "abn",
    date: "2024-01-31T16:00:00.000Z",
    client_id: "",
    client_fullname: "Kerry Hickman",
    client_address: "PO BOX 25 Bentley WA 6982 Australia",
    client_number: "12345444",
    user_fullname: "Jared Stanbrook",
    user_bsb: "036087",
    user_account: "886813",
    user_bank: "Westpac Banking Corporation",
    user_abn: "62385109727",
    user_phone: "0418 407 644",
    user_email: "Jared.Stanbrook@outlook.com",
    user_address: "19 Hopkins Pl, Waikiki WA 6169",
    service: [
        {
            service_date: "2024-01-01T16:00:00.000Z",
            line_number: "",
            description: "Assistance with Social and Community Event",
            km: 0,
            km_rate: 0.85,
            hour: 0,
            hour_rate: 50,
        },
    ],
    status: "incomplete",
};

fs.writeFileSync(
    "./dist/config/config.json",
    JSON.stringify({
        form_field_configs: form_field_configs,
        form_configs: form_configs,
        table_configs: table_configs,
        table_field_configs: table_field_configs,
        serviceHeadings: serviceHeadings,
        emptyService: emptyService,
        emptyInvoice: emptyInvoice,
    })
);
*/
const fileContent = fs.readFileSync("./dist/config/config.json");
const config = JSON.parse(fileContent);
console.log(config.form_field_configs);
